import test from 'node:test';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
test('scroll.test', { timeout: 60000 }, async (t) => {
    const browser = await chromium.launch();
    t.after(() => browser.close());
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    await page.route('https://translate.googleapis.com/**', route => route.fulfill({ json: [[['译文内容\n'.repeat(300), 'hello']], null, 'en'] }));
    await page.goto('http://127.0.0.1:3000/tools/translate');
    await page.locator('#translation-source').fill('hello world\n'.repeat(200));
    await page.getByRole('button', { name: '翻译', exact: true }).click();
    await page.locator('.translation-result').waitFor();
    const src = page.locator('#translation-source'), dst = page.getByRole('region', { name: '译文内容' }), toggle = page.getByRole('button', { name: '同步滚动', exact: true });
    const ratio = l => l.evaluate(e => e.scrollTop / (e.scrollHeight - e.clientHeight));
    await src.evaluate(e => e.scrollTop = (e.scrollHeight - e.clientHeight) * .6);
    await page.waitForTimeout(150);
    assert(Math.abs(await ratio(dst) - .6) < .01);
    await dst.evaluate(e => e.scrollTop = (e.scrollHeight - e.clientHeight) * .3);
    await page.waitForTimeout(150);
    assert(Math.abs(await ratio(src) - .3) < .01);
    await toggle.click();
    await src.evaluate(e => e.scrollTop = (e.scrollHeight - e.clientHeight) * .8);
    await page.waitForTimeout(150);
    assert(Math.abs(await ratio(dst) - .3) < .01);
    await toggle.click();
    await page.waitForTimeout(150);
    assert(Math.abs(await ratio(dst) - .8) < .01);
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth === innerWidth));
    console.log('PASS bidirectional sync, disabled independence, re-enable alignment, mobile overflow');
    await browser.close();
});
